RelativeTemplate/learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('others/', views.others, name='others'),
]

RelativeTemplate/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basic_app/',include('basic_app.urls')),
]

RelativeTemplate/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

RelativeTemplate/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict= {'text':'hello world', 'number':100}
    return render(request,'basic_app/index.html',context_dict)

def others(request):
    return render(request,'basic_app/others.html')

def relative(request):
    return render(request,'basic_app/relative_temp_page.html')

RelativeTemplate/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>BASE</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
    <nav class='navbar navbar-expand-lg'>
      <div class="container-fluid">
        <ul class='nav navbar-nav'>
          <li><a class='navbar-brand' href="{% url 'index' %}">BRAND</a></li>
          <li><a class='nav-link' href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class='nav-link' href="{% url 'basic_app:others' %}">Others</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

RelativeTemplate/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to index!</h1>
    <h2>{{text|cut:"hello"}}</h2>
    <h2>{{number|add:"90"}}</h2>
  {% endblock %}

RelativeTemplate/learning_templates/templates/basic_app/others.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to Others!</h1>
    <h2>Extended Others!!</h2>
  {% endblock %}

RelativeTemplate/learning_templates/templates/basic_app/relative_temp_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to Relative Template page</h1>
  </body>
</html>